// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtbl-sUIO8HfCxy1DvNazus06xISek0l0',
    appId: '1:972583496173:web:5e97d94c4406e6b63e1fe4',
    messagingSenderId: '972583496173',
    projectId: 'gymmate-ai-11f33',
    authDomain: 'gymmate-ai-11f33.firebaseapp.com',
    storageBucket: 'gymmate-ai-11f33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIcl8vulxXnvTGM3opJCZEcf0_hHF083o',
    appId: '1:972583496173:android:3f6a0b2345c9a21e3e1fe4',
    messagingSenderId: '972583496173',
    projectId: 'gymmate-ai-11f33',
    storageBucket: 'gymmate-ai-11f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqeOlEl-zYXaUXBrjbSLQCuyjHjcVcT_M',
    appId: '1:972583496173:ios:1dd63f294e55a3703e1fe4',
    messagingSenderId: '972583496173',
    projectId: 'gymmate-ai-11f33',
    storageBucket: 'gymmate-ai-11f33.firebasestorage.app',
    iosClientId: '972583496173-cbsfnohs1e0e9reejnd10rj7mmfcs5du.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmateAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqeOlEl-zYXaUXBrjbSLQCuyjHjcVcT_M',
    appId: '1:972583496173:ios:1dd63f294e55a3703e1fe4',
    messagingSenderId: '972583496173',
    projectId: 'gymmate-ai-11f33',
    storageBucket: 'gymmate-ai-11f33.firebasestorage.app',
    iosClientId: '972583496173-cbsfnohs1e0e9reejnd10rj7mmfcs5du.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymmateAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtbl-sUIO8HfCxy1DvNazus06xISek0l0',
    appId: '1:972583496173:web:f284086d094c43cf3e1fe4',
    messagingSenderId: '972583496173',
    projectId: 'gymmate-ai-11f33',
    authDomain: 'gymmate-ai-11f33.firebaseapp.com',
    storageBucket: 'gymmate-ai-11f33.firebasestorage.app',
  );
}
